apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorecard-server-deployment
spec:
  selector:
    matchLabels:
      app: scorecard
  replicas: 1
  template:
    metadata:
      labels:
        app: scorecard
        env: master
    spec:
      containers:
      - name: scorecard
        image: gcr.io/radiant-night-256502/github.com/magnusandy/scorecard-ts
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: scorecard-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    app: scorecard